const data = {
  paneProperties: {
    // topMargin: 50,
    bottomMargin: 25,
    background: '#181818',
    gridProperties: {
      color: '#E6E6E6',
    },
    vertGridProperties: {
      color: '#28343C',
    },
    horzGridProperties: {
      color: '#28343C',
    },
    crossHairProperties: {
      color: '#626c73',
      style: 2,
      transparency: 0,
      width: 1,
    },
    leftAxisProperties: {
      autoScale: true,
      autoScaleDisabled: false,
      percentage: false,
      percentageDisabled: false,
      log: false,
      logDisabled: false,
      alignLabels: true,
    },
    rightAxisProperties: {
      autoScale: true,
      autoScaleDisabled: false,
      percentage: false,
      percentageDisabled: false,
      log: false,
      logDisabled: false,
      alignLabels: true,
    },
    overlayPropreties: {
      autoScale: true,
      autoScaleDisabled: false,
      percentage: false,
      percentageDisabled: false,
      log: false,
      logDisabled: false,
      alignLabels: true,
    },
  },
  scalesProperties: {
    showLeftScale: false,
    showRightScale: true,
    backgroundColor: '#1b262d',
    lineColor: '#555',
    textColor: '#999',
    fontSize: 11,
    scaleSeriesOnly: false,
    showSeriesLastValue: true,
    showStudyLastValue: false,
    showSymbolLabels: false,
    showStudyPlotLabels: false,
  },
  mainSeriesProperties: {
    style: 9,
    esdShowDividends: true,
    esdShowSplits: true,
    esdShowEarnings: true,
    esdShowBreaks: false,
    esdBreaksStyle: {
      color: 'rgba( 226, 116, 91, 1)',
      style: 2,
      width: 1,
    },
    esdFlagSize: 2,
    showCountdown: false,
    showInDataWindow: true,
    visible: true,
    silentIntervalChange: false,
    showPriceLine: true,
    priceLineWidth: 1,
    lockScale: false,
    minTick: 'default',
    extendedHours: false,
    sessVis: false,
    statusViewStyle: {
      fontSize: 17,
      showExchange: true,
      showInterval: true,
      showSymbolAsDescription: false,
    },
    candleStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      drawWick: true,
      drawBorder: true,
      borderColor: 'rgba( 55, 134, 88, 1)',
      borderUpColor: 'rgba( 34, 84, 55, 1)',
      borderDownColor: 'rgba( 91, 26, 19, 1)',
      wickColor: 'rgba( 115, 115, 117, 1)',
      wickUpColor: 'rgba( 115, 115, 117, 1)',
      wickDownColor: 'rgba( 115, 115, 117, 1)',
      barColorsOnPrevClose: false,
    },
    // 这里是蜡烛图的颜色
    hollowCandleStyle: {
      upColor: '#3DE777',
      downColor: '#F04D64',
      drawWick: true,
      drawBorder: true,
      borderColor: '#C400CB',
      borderUpColor: '#3DE777',
      borderDownColor: '#F04D64',
      wickColor: 'rgba( 115, 115, 117, 1)',
      wickUpColor: '#3DE777',
      wickDownColor: '#F04D64',
    },
    haStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      drawWick: true,
      drawBorder: true,
      borderColor: 'rgba( 55, 134, 88, 1)',
      borderUpColor: 'rgba( 34, 84, 55, 1)',
      borderDownColor: 'rgba( 91, 26, 19, 1)',
      wickColor: 'rgba( 115, 115, 117, 1)',
      wickUpColor: 'rgba( 115, 115, 117, 1)',
      wickDownColor: 'rgba( 115, 115, 117, 1)',
      showRealLastPrice: false,
      barColorsOnPrevClose: false,
    },
    barStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      barColorsOnPrevClose: false,
      dontDrawOpen: false,
    },
    lineStyle: {
      color: 'rgba( 60, 120, 216, 1)',
      linestyle: 0,
      linewidth: 1,
      priceSource: 'close',
      styleType: 2,
    },
    areaStyle: {
      color1: 'rgba( 96, 96, 144, 0.5)',
      color2: 'rgba( 1, 246, 245, 0.5)',
      linecolor: 'rgba( 0, 148, 255, 1)',
      linestyle: 0,
      linewidth: 1,
      priceSource: 'close',
      transparency: 100,
    },
    priceAxisProperties: {
      autoScale: true,
      autoScaleDisabled: false,
      percentage: false,
      percentageDisabled: false,
      log: false,
      logDisabled: false,
    },
    renkoStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      borderUpColor: 'rgba( 34, 84, 55, 1)',
      borderDownColor: 'rgba( 91, 26, 19, 1)',
      upColorProjection: 'rgba( 74, 214, 190, 1)',
      downColorProjection: 'rgba( 214, 73, 207, 1)',
      borderUpColorProjection: 'rgba( 34, 84, 55, 1)',
      borderDownColorProjection: 'rgba( 91, 26, 19, 1)',
      inputs: {
        source: 'close',
        boxSize: 3,
        style: 'ATR',
        atrLength: 14,
      },
      inputInfo: {
        source: {
          name: 'Source',
        },
        boxSize: {
          name: 'Box size',
        },
        style: {
          name: 'Style',
        },
        atrLength: {
          name: 'ATR Length',
        },
      },
    },
    pbStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      borderUpColor: 'rgba( 34, 84, 55, 1)',
      borderDownColor: 'rgba( 91, 26, 19, 1)',
      upColorProjection: 'rgba( 74, 214, 190, 1)',
      downColorProjection: 'rgba( 214, 73, 207, 1)',
      borderUpColorProjection: 'rgba( 34, 84, 55, 1)',
      borderDownColorProjection: 'rgba( 91, 26, 19, 1)',
      inputs: {
        source: 'close',
        lb: 3,
      },
      inputInfo: {
        source: {
          name: 'Source',
        },
        lb: {
          name: 'Number of line',
        },
      },
    },
    kagiStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      upColorProjection: 'rgba( 74, 214, 190, 1)',
      downColorProjection: 'rgba( 214, 73, 207, 1)',
      inputs: {
        source: 'close',
        style: 'ATR',
        atrLength: 14,
        reversalAmount: 1,
      },
      inputInfo: {
        source: {
          name: 'Source',
        },
        style: {
          name: 'Style',
        },
        atrLength: {
          name: 'ATR Length',
        },
        reversalAmount: {
          name: 'Reversal amount',
        },
      },
    },
    pnfStyle: {
      upColor: 'rgba( 107, 165, 131, 1)',
      downColor: 'rgba( 215, 84, 66, 1)',
      upColorProjection: 'rgba( 74, 214, 190, 1)',
      downColorProjection: 'rgba( 214, 73, 207, 1)',
      inputs: {
        sources: 'HL',
        reversalAmount: 3,
        boxSize: 1,
        style: 'ATR',
        atrLength: 14,
      },
      inputInfo: {
        sources: {
          name: 'Source',
        },
        boxSize: {
          name: 'Box size',
        },
        reversalAmount: {
          name: 'Reversal amount',
        },
        style: {
          name: 'Style',
        },
        atrLength: {
          name: 'ATR Length',
        },
      },
    },
  },
  symbolWatermarkProperties: {
    color: 'rgba(0, 0, 0, 0)',
    transparency: 100,
  },
  chartEventsSourceProperties: {
    visible: true,
    futureOnly: true,
    breaks: {
      color: 'rgba(85, 85, 85, 1)',
      visible: false,
      style: 2,
      width: 1,
    },
  },
  tradingProperties: {
    showPositions: true,
    showOrders: true,
    showExecutions: true,
    extendLeft: true,
    lineLength: 5,
    lineWidth: 1,
    lineStyle: 2,
  },
  alertsProperties: {
    labels: {
      visible: true,
      color: 'rgba( 215, 84, 66, 1)',
      highlightColor: 'rgba( 255, 255, 51, 1)',
      hoverColor: 'rgba( 245, 227, 135, 1)',
      line: {
        visible: true,
        style: 2,
        width: 1,
      },
    },
    fakeLabels: {
      visible: true,
      color: 'rgba( 119, 119, 119, 1)',
      line: {
        visible: true,
        style: 2,
        width: 1,
      },
    },
    drawingIcon: {
      color: 'rgba( 170, 170, 170, 1)',
    },
  },
};

export default data;
